/**
 * lib/ticker-map.ts
 *
 * Maps company names (as they appear in lib/tiers.ts) to their primary
 * exchange ticker symbols. Only publicly traded companies are included.
 * Private companies, subsidiaries, and unlisted firms are intentionally omitted.
 *
 * Exchange suffixes follow Yahoo Finance convention:
 *   .T  = Tokyo Stock Exchange
 *   .KS = Korea Stock Exchange
 *   .TW = Taiwan Stock Exchange
 *   .HK = Hong Kong Stock Exchange
 *   .DE = XETRA (Germany)
 *   .AS = Amsterdam (Netherlands)
 *   .PA = Paris
 *   .L  = London
 *   .OL = Oslo
 *   .AX = ASX (Australia)
 *   .ST = Stockholm
 *   No suffix = US (NYSE / NASDAQ)
 */

export interface TickerEntry {
  symbol: string
  /** Friendly exchange label shown in the UI */
  exchange: string
}

export const TICKER_MAP: Record<string, TickerEntry> = {
  // ── TIER 1: Fabless Designers ──────────────────────────────────────────────
  "Nvidia":                    { symbol: "NVDA",      exchange: "NASDAQ" },
  "AMD":                       { symbol: "AMD",       exchange: "NASDAQ" },
  "Apple":                     { symbol: "AAPL",      exchange: "NASDAQ" },
  "Qualcomm":                  { symbol: "QCOM",      exchange: "NASDAQ" },
  "Broadcom":                  { symbol: "AVGO",      exchange: "NASDAQ" },
  "MediaTek":                  { symbol: "2454.TW",   exchange: "TWSE" },
  "Marvell Technology":        { symbol: "MRVL",      exchange: "NASDAQ" },
  "Amazon Web Services":       { symbol: "AMZN",      exchange: "NASDAQ" },
  "Google":                    { symbol: "GOOGL",     exchange: "NASDAQ" },
  "Microsoft":                 { symbol: "MSFT",      exchange: "NASDAQ" },
  "Meta Platforms":            { symbol: "META",      exchange: "NASDAQ" },
  "Tesla":                     { symbol: "TSLA",      exchange: "NASDAQ" },
  "Cisco Systems":             { symbol: "CSCO",      exchange: "NASDAQ" },
  "IBM":                       { symbol: "IBM",       exchange: "NYSE" },
  "Realtek Semiconductor":     { symbol: "2379.TW",   exchange: "TWSE" },
  "Novatek Microelectronics":  { symbol: "3034.TW",   exchange: "TWSE" },
  "Cirrus Logic":              { symbol: "CRUS",      exchange: "NASDAQ" },
  "Skyworks Solutions":        { symbol: "SWKS",      exchange: "NASDAQ" },
  "Qorvo":                     { symbol: "QRVO",      exchange: "NASDAQ" },
  "Monolithic Power Systems":  { symbol: "MPWR",      exchange: "NASDAQ" },
  "Ambarella":                 { symbol: "AMBA",      exchange: "NASDAQ" },
  "Lattice Semiconductor":     { symbol: "LSCC",      exchange: "NASDAQ" },
  "Synaptics":                 { symbol: "SYNA",      exchange: "NASDAQ" },
  "Wolfspeed":                 { symbol: "WOLF",      exchange: "NYSE" },
  "Nordic Semiconductor":      { symbol: "NOD.OL",    exchange: "Oslo" },
  "Macom Technology Solutions":{ symbol: "MTSI",      exchange: "NASDAQ" },
  "Semtech":                   { symbol: "SMTC",      exchange: "NASDAQ" },
  "MaxLinear":                 { symbol: "MXL",       exchange: "NASDAQ" },
  "Allegro MicroSystems":      { symbol: "ALGM",      exchange: "NASDAQ" },
  "Rambus":                    { symbol: "RMBS",      exchange: "NASDAQ" },
  "Silicon Laboratories":      { symbol: "SLAB",      exchange: "NASDAQ" },
  "Himax Technologies":        { symbol: "HIMX",      exchange: "NASDAQ" },
  "Hailo":                     { symbol: "HALO",      exchange: "NASDAQ" },
  "BrainChip":                 { symbol: "BRN.AX",    exchange: "ASX" },

  // ── TIER 2: Foundries, IDMs & OSATs ───────────────────────────────────────
  "TSMC":                      { symbol: "TSM",       exchange: "NYSE" },
  "Samsung Foundry":           { symbol: "005930.KS", exchange: "KRX" },
  "Intel Foundry":             { symbol: "INTC",      exchange: "NASDAQ" },
  "SK Hynix":                  { symbol: "000660.KS", exchange: "KRX" },
  "Micron Technology":         { symbol: "MU",        exchange: "NASDAQ" },
  "GlobalFoundries":           { symbol: "GFS",       exchange: "NASDAQ" },
  "UMC":                       { symbol: "UMC",       exchange: "NYSE" },
  "SMIC":                      { symbol: "0981.HK",   exchange: "HKEX" },
  "Texas Instruments":         { symbol: "TXN",       exchange: "NASDAQ" },
  "STMicroelectronics":        { symbol: "STM",       exchange: "NYSE" },
  "Infineon Technologies":     { symbol: "IFX.DE",    exchange: "XETRA" },
  "NXP Semiconductors":        { symbol: "NXPI",      exchange: "NASDAQ" },
  "Analog Devices":            { symbol: "ADI",       exchange: "NASDAQ" },
  "Renesas Electronics":       { symbol: "6723.T",    exchange: "TSE" },
  "Microchip Technology":      { symbol: "MCHP",      exchange: "NASDAQ" },
  "onsemi":                    { symbol: "ON",        exchange: "NASDAQ" },
  "Sony Semiconductor Solutions": { symbol: "6758.T", exchange: "TSE" },
  "Kioxia":                    { symbol: "285A.T",    exchange: "TSE" },
  "Tower Semiconductor":       { symbol: "TSEM",      exchange: "NASDAQ" },
  "ASE Group":                 { symbol: "ASX",       exchange: "NYSE" },
  "Amkor Technology":          { symbol: "AMKR",      exchange: "NASDAQ" },
  "Hua Hong Semiconductor":    { symbol: "1347.HK",   exchange: "HKEX" },
  "Win Semiconductors":        { symbol: "3105.TW",   exchange: "TWSE" },
  "DB Hitek":                  { symbol: "000990.KS", exchange: "KRX" },
  "ChipMOS Technologies":      { symbol: "IMOS",      exchange: "NASDAQ" },
  "Rohm Semiconductor":        { symbol: "6963.T",    exchange: "TSE" },
  "SkyWater Technology":       { symbol: "SKYT",      exchange: "NASDAQ" },
  "X-Fab":                     { symbol: "XFAB.DE",   exchange: "XETRA" },
  "Powertech Technology":      { symbol: "6239.TW",   exchange: "TWSE" },

  // ── TIER 3: SME Integrators ───────────────────────────────────────────────
  "ASML":                      { symbol: "ASML",      exchange: "NASDAQ" },
  "Applied Materials":         { symbol: "AMAT",      exchange: "NASDAQ" },
  "Lam Research":              { symbol: "LRCX",      exchange: "NASDAQ" },
  "Tokyo Electron":            { symbol: "8035.T",    exchange: "TSE" },
  "KLA Corporation":           { symbol: "KLAC",      exchange: "NASDAQ" },
  "Nikon Corporation":         { symbol: "7731.T",    exchange: "TSE" },
  "Canon Inc.":                { symbol: "CAJ",       exchange: "NYSE" },
  "Screen Holdings":           { symbol: "7735.T",    exchange: "TSE" },
  "ASM International":         { symbol: "ASMIY",     exchange: "OTC" },
  "Hitachi High-Tech":         { symbol: "8036.T",    exchange: "TSE" },
  "Advantest":                 { symbol: "ATE",       exchange: "NYSE" },
  "Teradyne":                  { symbol: "TER",       exchange: "NASDAQ" },
  "Kokusai Electric":          { symbol: "6525.T",    exchange: "TSE" },
  "Onto Innovation":           { symbol: "ONTO",      exchange: "NYSE" },
  "Veeco Instruments":         { symbol: "VECO",      exchange: "NASDAQ" },
  "BE Semiconductor Industries": { symbol: "BESI.AS", exchange: "AEX" },
  "Kulicke & Soffa":           { symbol: "KLIC",      exchange: "NASDAQ" },
  "Suss MicroTec":             { symbol: "SMHN.DE",   exchange: "XETRA" },
  "Disco Corporation":         { symbol: "6146.T",    exchange: "TSE" },
  "Tokyo Seimitsu":            { symbol: "7729.T",    exchange: "TSE" },
  "ACM Research":              { symbol: "ACMR",      exchange: "NASDAQ" },
  "Park Systems":              { symbol: "140860.KS", exchange: "KRX" },
  "FormFactor":                { symbol: "FORM",      exchange: "NASDAQ" },
  "Cohu":                      { symbol: "COHU",      exchange: "NASDAQ" },
  "Camtek":                    { symbol: "CAMT",      exchange: "NASDAQ" },
  "Nordson Corporation":       { symbol: "NDSN",      exchange: "NASDAQ" },
  "IPG Photonics":             { symbol: "IPGP",      exchange: "NASDAQ" },
  "Axcelis Technologies":      { symbol: "ACLS",      exchange: "NASDAQ" },
  "Nova Measuring Instruments":{ symbol: "NVMI",      exchange: "NASDAQ" },
  "Hanmi Semiconductor":       { symbol: "042700.KS", exchange: "KRX" },

  // ── TIER 4: Subsystems & Modules ──────────────────────────────────────────
  "MKS Instruments":           { symbol: "MKSI",      exchange: "NASDAQ" },
  "Advanced Energy":           { symbol: "AEIS",      exchange: "NASDAQ" },
  "Entegris":                  { symbol: "ENTG",      exchange: "NASDAQ" },
  "Coherent":                  { symbol: "COHR",      exchange: "NYSE" },
  "Jenoptik":                  { symbol: "JEN.DE",    exchange: "XETRA" },
  "Ultra Clean Holdings":      { symbol: "UCTT",      exchange: "NASDAQ" },
  "Ichor Systems":             { symbol: "ICHR",      exchange: "NASDAQ" },
  "Parker Hannifin":           { symbol: "PH",        exchange: "NYSE" },
  "Yaskawa Electric":          { symbol: "6506.T",    exchange: "TSE" },
  "Fanuc":                     { symbol: "6954.T",    exchange: "TSE" },
  "NSK Ltd.":                  { symbol: "6471.T",    exchange: "TSE" },
  "NTN Corporation":           { symbol: "6472.T",    exchange: "TSE" },
  "SKF Group":                 { symbol: "SKF-B.ST",  exchange: "OMX" },
  "Daihen Corporation":        { symbol: "6622.T",    exchange: "TSE" },
  "XP Power":                  { symbol: "XPP.L",     exchange: "LSE" },
  "Inficon":                   { symbol: "IFCN.SW",   exchange: "SIX" },
  "Edwards Vacuum":            { symbol: "ATLKY",     exchange: "OTC" },
  "Pfeiffer Vacuum":           { symbol: "PFV.DE",    exchange: "XETRA" },
  "Ebara Corporation":         { symbol: "6361.T",    exchange: "TSE" },
  "Comet Group":               { symbol: "COTN.SW",   exchange: "SIX" },
  "Moog Inc.":                 { symbol: "MOG-A",     exchange: "NYSE" },
  "Horiba":                    { symbol: "6856.T",    exchange: "TSE" },

  // ── TIER 5: Precision Components ──────────────────────────────────────────
  "Corning Inc.":              { symbol: "GLW",       exchange: "NYSE" },
  "Hoya Corporation":          { symbol: "7741.T",    exchange: "TSE" },
  "Frencken Group":            { symbol: "E28.SI",    exchange: "SGX" },
  "Renishaw":                  { symbol: "RSW.L",     exchange: "LSE" },
  "Kyocera Corporation":       { symbol: "KYO",       exchange: "NYSE" },
  "AGC Inc.":                  { symbol: "5201.T",    exchange: "TSE" },
  "Edmund Optics":             { symbol: "EDMO",      exchange: "OTC" },
  "Materion":                  { symbol: "MTRN",      exchange: "NYSE" },
  "Mitutoyo":                  { symbol: "7751.T",    exchange: "TSE" },
  "Maxon Motor":                { symbol: "MAXN",      exchange: "OTC" },
  "Samtec":                    { symbol: "SMTK",      exchange: "OTC" },
  "TDK-Lambda":                { symbol: "6762.T",    exchange: "TSE" },
  "Hirose Electric":           { symbol: "6806.T",    exchange: "TSE" },
  "Heraeus Conamic":           { symbol: "HERA.DE",   exchange: "XETRA" },

  // ── TIER 6: Process Materials ──────────────────────────────────────────────
  "Shin-Etsu Chemical":        { symbol: "4063.T",    exchange: "TSE" },
  "Sumco Corporation":         { symbol: "3436.T",    exchange: "TSE" },
  "Siltronic AG":              { symbol: "WAF.DE",    exchange: "XETRA" },
  "SK Siltron":                { symbol: "361670.KS", exchange: "KRX" },
  "JSR Corporation":           { symbol: "4185.T",    exchange: "TSE" },
  "Tokyo Ohka Kogyo":          { symbol: "4186.T",    exchange: "TSE" },
  "DuPont Electronic Solutions": { symbol: "DD",      exchange: "NYSE" },
  "Merck KGaA":                { symbol: "MRK.DE",    exchange: "XETRA" },
  "Linde plc":                 { symbol: "LIN",       exchange: "NYSE" },
  "Air Liquide":               { symbol: "AI.PA",     exchange: "Euronext" },
  "Resonac":                   { symbol: "4004.T",    exchange: "TSE" },
  "BASF Electronic Materials": { symbol: "BAS.DE",    exchange: "XETRA" },
  "Umicore":                   { symbol: "UMI.BR",    exchange: "Euronext" },
  "Ibiden Co. Ltd.":           { symbol: "4062.T",    exchange: "TSE" },
  "Unimicron Technology":      { symbol: "3037.TW",   exchange: "TWSE" },
  "AT&S":                      { symbol: "ATS.VI",    exchange: "Vienna" },
  "Air Products and Chemicals":{ symbol: "APD",       exchange: "NYSE" },
  "Solvay":                    { symbol: "SOLVY",     exchange: "OTC" },
  "Arkema":                    { symbol: "AKE.PA",    exchange: "Euronext" },
  "Nitto Denko":                { symbol: "6988.T",    exchange: "TSE" },
  "Sekisui Chemical":          { symbol: "4204.T",    exchange: "TSE" },
  "Dexerials Corporation":     { symbol: "4980.T",    exchange: "TSE" },
  "Tanaka Precious Metals":    { symbol: "TNCKY",     exchange: "OTC" },
  "Adeka Corporation":         { symbol: "4401.T",    exchange: "TSE" },
  "Fujifilm Electronic Materials": { symbol: "FUJIY", exchange: "OTC" },
  "Sumitomo Chemical":         { symbol: "SOMMY",     exchange: "OTC" },

  // ── TIER 7: Extraction & Refining ─────────────────────────────────────────
  "Wacker Chemie":             { symbol: "WCH.DE",    exchange: "XETRA" },
  "OCI Company":               { symbol: "010060.KS", exchange: "KRX" },
  "Tokuyama Corporation":      { symbol: "4043.T",    exchange: "TSE" },
  "REC Silicon":               { symbol: "RECSI.OL",  exchange: "Oslo" },
  "Lynas Rare Earths":         { symbol: "LYC.AX",    exchange: "ASX" },
  "MP Materials":              { symbol: "MP",        exchange: "NYSE" },
  "Iluka Resources":           { symbol: "ILU.AX",    exchange: "ASX" },
  "Tronox":                    { symbol: "TROX",      exchange: "NYSE" },
  "Rio Tinto":                 { symbol: "RIO",       exchange: "NYSE" },
  "BHP Group":                 { symbol: "BHP",       exchange: "NYSE" },
  "Freeport-McMoRan":          { symbol: "FCX",       exchange: "NYSE" },
  "Antofagasta plc":           { symbol: "ANTO.L",    exchange: "LSE" },
  "Southern Copper Corporation":{ symbol: "SCCO",     exchange: "NYSE" },
  "Glencore":                  { symbol: "GLEN.L",    exchange: "LSE" },
  "Anglo American":            { symbol: "AAL.L",     exchange: "LSE" },
  "Vale S.A.":                 { symbol: "VALE",      exchange: "NYSE" },
  "Alcoa Corporation":         { symbol: "AA",        exchange: "NYSE" },
  "Norsk Hydro":               { symbol: "NHY.OL",    exchange: "Oslo" },
  "Sumitomo Metal Mining":     { symbol: "SMMYY",     exchange: "OTC" },
  "Mitsubishi Materials":      { symbol: "MIMTF",     exchange: "OTC" },
  "Albemarle Corporation":     { symbol: "ALB",       exchange: "NYSE" },
  "SQM":                       { symbol: "SQM",       exchange: "NYSE" },
  "Dow Chemical":              { symbol: "DOW",       exchange: "NYSE" },
  "ExxonMobil Chemical":       { symbol: "XOM",       exchange: "NYSE" },
  "Shell Chemical":            { symbol: "SHEL",      exchange: "NYSE" },
  "Chemours":                  { symbol: "CC",        exchange: "NYSE" },
  "Asahi Kasei":                { symbol: "AHKSY",     exchange: "OTC" },
  "Tosoh Corporation":         { symbol: "TOSHF",     exchange: "OTC" },
  "Mitsui Chemicals":          { symbol: "MITSY",     exchange: "OTC" },
  "Tokai Carbon":              { symbol: "5301.T",    exchange: "TSE" },

  // ── T1 · Fabless Designers (new) ──────────────────────────────────────────────
  "Arm Holdings": { symbol: "ARM", exchange: "NASDAQ" },
  "Mobileye": { symbol: "MBLY", exchange: "NASDAQ" },
  "Diodes Incorporated": { symbol: "DIOD", exchange: "NASDAQ" },
  "Power Integrations": { symbol: "POWI", exchange: "NASDAQ" },
  "indie Semiconductor": { symbol: "INDI", exchange: "NASDAQ" },
  "SiTime": { symbol: "SITM", exchange: "NASDAQ" },
  "Navitas Semiconductor": { symbol: "NVTS", exchange: "NASDAQ" },
  "Astera Labs": { symbol: "ALAB", exchange: "NASDAQ" },
  "Credo Technology Group": { symbol: "CRDO", exchange: "NASDAQ" },
  "Silicon Motion Technology": { symbol: "SIMO", exchange: "NASDAQ" },
  "Andes Technology": { symbol: "6533.TWO", exchange: "TPEx" },
  "Faraday Technology": { symbol: "3035.TW", exchange: "TWSE" },
  "Global Unichip Corp": { symbol: "3443.TW", exchange: "TWSE" },
  "VIA Technologies": { symbol: "2388.TW", exchange: "TWSE" },
  "Etron Technology": { symbol: "5351.TWO", exchange: "TPEx" },
  "Parade Technologies": { symbol: "4966.TW", exchange: "TWSE" },
  "Phison Electronics": { symbol: "8299.TWO", exchange: "TPEx" },
  "Nuvoton Technology": { symbol: "4919.TW", exchange: "TWSE" },
  "Socionext": { symbol: "6526.T", exchange: "TSE" },
  "MegaChips Corporation": { symbol: "6875.T", exchange: "TSE" },
  "Melexis": { symbol: "MELE.BR", exchange: "Euronext" },
  "Sequans Communications": { symbol: "SQNS", exchange: "NASDAQ" },
  "Kalray": { symbol: "ALKAL.PA", exchange: "Euronext" },
  "u-blox": { symbol: "UBXN.SW", exchange: "SIX" },
  "LX Semicon": { symbol: "108320.KS", exchange: "KRX" },
  "Telechips": { symbol: "054450.KQ", exchange: "KOSDAQ" },
  "eMemory Technology": { symbol: "3529.TWO", exchange: "TPEx" },
  "M31 Technology": { symbol: "6643.TWO", exchange: "TPEx" },
  "VeriSilicon": { symbol: "688521.SS", exchange: "STAR" },
  "Espressif Systems": { symbol: "688018.SS", exchange: "STAR" },
  "GigaDevice Semiconductor": { symbol: "603986.SS", exchange: "SSE" },
  "Horizon Robotics": { symbol: "9660.HK", exchange: "HKEX" },
  "Cambricon Technologies": { symbol: "688256.SS", exchange: "STAR" },

  // ── T2 · Foundries, IDMs & OSATs (new) ──────────────────────────────────────────────
  "Loongson Technology": { symbol: "688047.SS", exchange: "STAR" },
  "Allwinner Technology": { symbol: "300458.SZ", exchange: "SZSE" },
  "Vishay Intertechnology": { symbol: "VSH", exchange: "NYSE" },
  "Littelfuse": { symbol: "LFUS", exchange: "NASDAQ" },
  "ams OSRAM": { symbol: "AMS.SW", exchange: "SIX" },
  "Macronix International": { symbol: "2337.TW", exchange: "TWSE" },
  "Winbond Electronics": { symbol: "2344.TW", exchange: "TWSE" },
  "Powerchip Semiconductor Mfg Corp": { symbol: "6770.TW", exchange: "TWSE" },
  "Magnachip Semiconductor": { symbol: "MX", exchange: "NYSE" },
  "Hangzhou Silan Microelectronics": { symbol: "600460.SS", exchange: "SSE" },
  "Fuji Electric": { symbol: "6504.T", exchange: "TSE" },
  "Mitsubishi Electric": { symbol: "6503.T", exchange: "TSE" },
  "Sanken Electric": { symbol: "6707.T", exchange: "TSE" },
  "Unisem": { symbol: "UNISEM.KL", exchange: "Bursa" },

  // ── T3 · Equipment (new) ──────────────────────────────────────────────
  "Inari Amertron": { symbol: "INARI.KL", exchange: "Bursa" },
  "CG Semi": { symbol: "CGPOWER.NS", exchange: "NSE" },
  "Lasertec Corporation": { symbol: "6920.T", exchange: "TSE" },
  "Ulvac Inc": { symbol: "6728.T", exchange: "TSE" },
  "Mycronic AB": { symbol: "MYCR.ST", exchange: "OMX" },
  "Oxford Instruments": { symbol: "OXIG.L", exchange: "LSE" },
  "Aixtron SE": { symbol: "AIXA.DE", exchange: "XETRA" },
  "Chroma ATE": { symbol: "2360.TW", exchange: "TWSE" },
  "Aehr Test Systems": { symbol: "AEHR", exchange: "NASDAQ" },
  "inTEST Corporation": { symbol: "INTT", exchange: "NYSE American" },
  "Bruker Corporation": { symbol: "BRKR", exchange: "NASDAQ" },

  // ── T4 · Subsystems (new) ──────────────────────────────────────────────
  "Thermo Fisher Scientific": { symbol: "TMO", exchange: "NYSE" },
  "Test Research Inc": { symbol: "6209.TW", exchange: "TWSE" },
  "Lumentum Holdings": { symbol: "LITE", exchange: "NASDAQ" },
  "nLIGHT Inc": { symbol: "LASR", exchange: "NASDAQ" },
  "Han's Laser": { symbol: "002008.SZ", exchange: "SZSE" },
  "Agilent Technologies": { symbol: "A", exchange: "NYSE" },
  "Hamamatsu Photonics": { symbol: "6965.T", exchange: "TSE" },
  "Donaldson Company": { symbol: "DCI", exchange: "NYSE" },
  "Daikin Industries": { symbol: "6367.T", exchange: "TSE" },
  "Johnson Controls": { symbol: "JCI", exchange: "NYSE" },
  "Trane Technologies": { symbol: "TT", exchange: "NYSE" },
  "NGK Insulators": { symbol: "5333.T", exchange: "TSE" },
  "Keyence Corporation": { symbol: "6861.T", exchange: "TSE" },
  "Omron Corporation": { symbol: "6645.T", exchange: "TSE" },
  "Eaton Corporation": { symbol: "ETN", exchange: "NYSE" },
  "Vertiv Holdings": { symbol: "VRT", exchange: "NYSE" },
  "Schneider Electric": { symbol: "SU.PA", exchange: "Euronext" },

  // ── T5 · Components (new) ──────────────────────────────────────────────
  "ABB Ltd": { symbol: "ABBN.SW", exchange: "SIX" },
  "Trelleborg Sealing Solutions": { symbol: "TRELB.ST", exchange: "OMX" },
  "AMETEK Inc": { symbol: "AME", exchange: "NYSE" },
  "3M Company": { symbol: "MMM", exchange: "NYSE" },
  "Nidec Corporation": { symbol: "6594.T", exchange: "TSE" },
  "Allied Motion Technologies": { symbol: "AMOT", exchange: "NASDAQ" },
  "Amphenol Corporation": { symbol: "APH", exchange: "NYSE" },
  "TE Connectivity": { symbol: "TEL", exchange: "NYSE" },
  "Schaeffler Group": { symbol: "SHA.DE", exchange: "XETRA" },
  "RBC Bearings": { symbol: "RBC", exchange: "NASDAQ" },
  "Nippon Electric Glass": { symbol: "5214.T", exchange: "TSE" },
  "CTS Corporation": { symbol: "CTS", exchange: "NYSE" },
  "Furukawa Electric": { symbol: "5801.T", exchange: "TSE" },
  "Sumitomo Electric Industries": { symbol: "5802.T", exchange: "TSE" },
  "Fujikura Ltd": { symbol: "5803.T", exchange: "TSE" },
  "Sensata Technologies": { symbol: "ST", exchange: "NYSE" },

  // ── T6 · Materials (new) ──────────────────────────────────────────────
  "TT Electronics": { symbol: "TTG.L", exchange: "LSE" },
  "Largan Precision": { symbol: "3008.TW", exchange: "TWSE" },
  "Soitec": { symbol: "SOI.PA", exchange: "Euronext" },
  "Celanese Corporation": { symbol: "CE", exchange: "NYSE" },
  "Eternal Materials": { symbol: "1717.TW", exchange: "TWSE" },
  "Samsung Electro-Mechanics": { symbol: "009150.KS", exchange: "KRX" },
  "LG Innotek": { symbol: "011070.KS", exchange: "KRX" },
  "Daeduck Electronics": { symbol: "008060.KS", exchange: "KRX" },
  "Zhen Ding Technology": { symbol: "4958.TW", exchange: "TWSE" },
  "TTM Technologies": { symbol: "TTMI", exchange: "NASDAQ" },
  "Mitsui High-tec": { symbol: "6966.T", exchange: "TSE" },
  "Toray Industries": { symbol: "3402.T", exchange: "TSE" },
  "Mitsubishi Chemical Group": { symbol: "4188.T", exchange: "TSE" },
  "Sumitomo Bakelite": { symbol: "4203.T", exchange: "TSE" },
  "Mitsubishi Gas Chemical": { symbol: "4182.T", exchange: "TSE" },
  "Kureha Corporation": { symbol: "4023.T", exchange: "TSE" },
  "Avantor Inc": { symbol: "AVTR", exchange: "NYSE" },
  "AXT Inc": { symbol: "AXTI", exchange: "NASDAQ" },
  "IQE plc": { symbol: "IQE.L", exchange: "LSE AIM" },
  "Kuraray Co": { symbol: "3405.T", exchange: "TSE" },
  "DIC Corporation": { symbol: "4631.T", exchange: "TSE" },

  // ── T7 · Mining & Extraction (new) ──────────────────────────────────────────────
  "Daicel Corporation": { symbol: "4202.T", exchange: "TSE" },
  "Hansol Chemical": { symbol: "014680.KS", exchange: "KRX" },
  "First Quantum Minerals": { symbol: "FM.TO", exchange: "TSX" },
  "Teck Resources": { symbol: "TECK", exchange: "NYSE" },
  "KGHM Polska Miedz": { symbol: "KGH.WA", exchange: "GPW" },
  "Zijin Mining Group": { symbol: "601899.SS", exchange: "SSE" },
  "Ganfeng Lithium": { symbol: "002460.SZ", exchange: "SZSE" },
  "Tianqi Lithium": { symbol: "002466.SZ", exchange: "SZSE" },
  "Pilbara Minerals": { symbol: "PLS.AX", exchange: "ASX" },
  "China Molybdenum": { symbol: "603993.SS", exchange: "SSE" },
  "Eramet": { symbol: "ERA.PA", exchange: "Euronext" },
  "China Hongqiao Group": { symbol: "1378.HK", exchange: "HKEX" },
  "Chalco": { symbol: "601600.SS", exchange: "SSE" },
  "UC Rusal": { symbol: "0486.HK", exchange: "HKEX" },
  "LyondellBasell Industries": { symbol: "LYB", exchange: "NYSE" },
  "Eastman Chemical Company": { symbol: "EMN", exchange: "NYSE" },
  "LG Chem": { symbol: "051910.KS", exchange: "KRX" },
  "Hanwha Solutions": { symbol: "009830.KS", exchange: "KRX" },
  "Lotte Chemical": { symbol: "011170.KS", exchange: "KRX" },
  "Sinopec": { symbol: "600028.SS", exchange: "SSE" },
  "PetroChina": { symbol: "601857.SS", exchange: "SSE" },
  "Reliance Industries": { symbol: "RELIANCE.NS", exchange: "NSE" },
  "South32": { symbol: "S32.AX", exchange: "ASX" },
  "Newmont Corporation": { symbol: "NEM", exchange: "NYSE" },
  "Barrick Gold": { symbol: "GOLD", exchange: "NYSE" },
  "Vedanta Limited": { symbol: "VEDL.NS", exchange: "NSE" },
  "Idemitsu Kosan": { symbol: "5019.T", exchange: "TSE" },
  "Almonty Industries": { symbol: "AII.TO", exchange: "TSX" },
  "5N Plus Inc": { symbol: "VNP.TO", exchange: "TSX" },
  "Yunnan Tin Group": { symbol: "000960.SZ", exchange: "SZSE" },
  "Imerys": { symbol: "NK.PA", exchange: "Euronext" },
  "Shenghe Resources": { symbol: "600392.SS", exchange: "SSE" },
  "Energy Fuels Inc": { symbol: "UUUU", exchange: "NYSE American" },
}

/** Returns the ticker entry for a company name, or null if not publicly traded. */
export function getTicker(companyName: string): TickerEntry | null {
  return TICKER_MAP[companyName] ?? null
}