/**
 * Maps TIERS company names → Yahoo Finance ticker symbols.
 * Private companies are intentionally omitted.
 * International tickers use Yahoo's exchange suffix format (e.g. 4063.T = Tokyo).
 */
export const TICKERS: Record<string, string> = {
  // ── T1 · Fabless Designers ──────────────────────────────────────────────
  "Nvidia":                    "NVDA",
  "AMD":                       "AMD",
  "Apple":                     "AAPL",
  "Qualcomm":                  "QCOM",
  "Broadcom":                  "AVGO",
  "MediaTek":                  "2454.TW",
  "Marvell Technology":        "MRVL",
  "Amazon Web Services":       "AMZN",
  "Google":                    "GOOGL",
  "Microsoft":                 "MSFT",
  "Meta Platforms":            "META",
  "Tesla":                     "TSLA",
  "Cisco Systems":             "CSCO",
  "IBM":                       "IBM",
  "Realtek Semiconductor":     "2379.TW",
  "Novatek Microelectronics":  "3034.TW",
  "Cirrus Logic":              "CRUS",
  "Skyworks Solutions":        "SWKS",
  "Qorvo":                     "QRVO",
  "Monolithic Power Systems":  "MPWR",
  "Ambarella":                 "AMBA",
  "Lattice Semiconductor":     "LSCC",
  "Synaptics":                 "SYNA",
  "Wolfspeed":                 "WOLF",
  "Nordic Semiconductor":      "NOD.OL",
  "Macom Technology Solutions":"MTSI",
  "Semtech":                   "SMTC",
  "MaxLinear":                 "MXL",
  "Allegro MicroSystems":      "ALGM",
  "Rambus":                    "RMBS",
  "CEVA":                      "CEVA",
  "Silicon Laboratories":      "SLAB",
  "Himax Technologies":        "HIMX",
  "BrainChip":                 "BRN.AX",

  // ── T2 · Foundries, IDMs & OSATs ────────────────────────────────────────
  "TSMC":                      "TSM",
  "Samsung Foundry":           "005930.KS",
  "Intel Foundry":             "INTC",
  "SK Hynix":                  "000660.KS",
  "Micron Technology":         "MU",
  "GlobalFoundries":           "GFS",
  "UMC":                       "UMC",
  "Texas Instruments":         "TXN",
  "STMicroelectronics":        "STM",
  "Infineon Technologies":     "IFX.DE",
  "NXP Semiconductors":        "NXPI",
  "Analog Devices":            "ADI",
  "Renesas Electronics":       "6723.T",
  "Microchip Technology":      "MCHP",
  "onsemi":                    "ON",
  "Kioxia":                    "285A.T",
  "Tower Semiconductor":       "TSEM",
  "ASE Group":                 "ASX",
  "Amkor Technology":          "AMKR",
  "Rohm Semiconductor":        "6963.T",
  "SkyWater Technology":       "SKYT",
  "X-Fab":                     "XFAB.PA",

  // ── T3 · Equipment ──────────────────────────────────────────────────────
  "ASML":                      "ASML",
  "Applied Materials":         "AMAT",
  "Lam Research":              "LRCX",
  "KLA Corporation":           "KLAC",
  "Nikon Corporation":         "7731.T",
  "Canon Inc.":                "CAJ",
  "ASM International":         "ASMIY",
  "Advantest":                 "ATEYY",
  "Teradyne":                  "TER",
  "Onto Innovation":           "ONTO",
  "Veeco Instruments":         "VECO",
  "BE Semiconductor Industries":"BESI.AS",
  "Kulicke & Soffa":           "KLIC",
  "Axcelis Technologies":      "ACLS",
  "FormFactor":                "FORM",
  "Cohu":                      "COHU",
  "Camtek":                    "CAMT",
  "Nordson Corporation":       "NDSN",
  "IPG Photonics":             "IPGP",
  "ACM Research":              "ACMR",

  // ── T4 · Subsystems ─────────────────────────────────────────────────────
  "MKS Instruments":           "MKSI",
  "Advanced Energy":           "AEIS",
  "Coherent":                  "COHR",
  "Parker Hannifin":           "PH",
  "Ultra Clean Holdings":      "UCTT",
  "Ichor Systems":             "ICHR",
  "Moog Inc.":                 "MOG.A",
  "Yaskawa Electric":          "6506.T",
  "Fanuc":                     "6954.T",
  "SKF Group":                 "SKF-B.ST",
  "XP Power":                  "XPP.L",
  "Pfeiffer Vacuum":           "PFV.DE",
  "Ebara Corporation":         "6361.T",

  // ── T5 · Components ─────────────────────────────────────────────────────
  "Corning Inc.":              "GLW",
  "Hoya Corporation":          "7741.T",
  "Kyocera Corporation":       "6971.T",
  "Renishaw":                  "RSW.L",
  "Materion":                  "MTRN",
  "Hirose Electric":           "6806.T",
  "Huber+Suhner":              "HUBN.SW",
  "TDK-Lambda":                "6762.T",

  // ── T6 · Materials ──────────────────────────────────────────────────────
  "Shin-Etsu Chemical":        "4063.T",
  "Sumco Corporation":         "3436.T",
  "Siltronic AG":              "WAF.DE",
  "DuPont Electronic Solutions":"DD",
  "Merck KGaA":                "MRK.DE",
  "Linde plc":                 "LIN",
  "Air Liquide":               "AI.PA",
  "Sumitomo Chemical":         "4005.T",
  "BASF Electronic Materials": "BAS.DE",
  "Umicore":                   "UMI.BR",
  "Honeywell Electronic Materials":"HON",
  "AT&S":                      "ATS.VI",
  "Nitto Denko":                "6988.T",
  "Air Products and Chemicals":"APD",
  "Arkema":                    "AKE.PA",
  "Solvay":                    "SOLVY",
  "Dexerials Corporation":     "4980.T",
  "Adeka Corporation":         "4401.T",

  // ── T7 · Mining & Extraction ────────────────────────────────────────────
  "Wacker Chemie":             "WCH.DE",
  "OCI Company":               "010060.KS",
  "REC Silicon":               "RECSI.OL",
  "Daqo New Energy":           "DQ",
  "Lynas Rare Earths":         "LYC.AX",
  "MP Materials":              "MP",
  "Iluka Resources":           "ILU.AX",
  "Tronox":                    "TROX",
  "Rio Tinto":                 "RIO",
  "BHP Group":                 "BHP",
  "Freeport-McMoRan":          "FCX",
  "Antofagasta plc":           "ANTO.L",
  "Southern Copper Corporation":"SCCO",
  "Anglo American":            "AAL.L",
  "Vale S.A.":                 "VALE",
  "Alcoa Corporation":         "AA",
  "Norsk Hydro":               "NHY.OL",
  "Albemarle Corporation":     "ALB",
  "SQM":                       "SQM",
  "Dow Chemical":              "DOW",
  "Chemours":                  "CC",
  "Asahi Kasei":               "3407.T",
  "Tosoh Corporation":         "4042.T",
  "Mitsui Chemicals":          "4183.T",

  // ── T1 · Fabless Designers (new) ──────────────────────────────────────────────
  "Arm Holdings":                 "ARM",
  "Mobileye":                     "MBLY",
  "Diodes Incorporated":          "DIOD",
  "Power Integrations":           "POWI",
  "indie Semiconductor":          "INDI",
  "SiTime":                       "SITM",
  "Navitas Semiconductor":        "NVTS",
  "Astera Labs":                  "ALAB",
  "Credo Technology Group":       "CRDO",
  "Silicon Motion Technology":    "SIMO",
  "Andes Technology":             "6533.TWO",
  "Faraday Technology":           "3035.TW",
  "Global Unichip Corp":          "3443.TW",
  "VIA Technologies":             "2388.TW",
  "Etron Technology":             "5351.TWO",
  "Parade Technologies":          "4966.TW",
  "Phison Electronics":           "8299.TWO",
  "Nuvoton Technology":           "4919.TW",
  "Socionext":                    "6526.T",
  "MegaChips Corporation":        "6875.T",
  "Melexis":                      "MELE.BR",
  "Sequans Communications":       "SQNS",
  "Kalray":                       "ALKAL.PA",
  "u-blox":                       "UBXN.SW",
  "LX Semicon":                   "108320.KS",
  "Telechips":                    "054450.KQ",
  "eMemory Technology":           "3529.TWO",
  "M31 Technology":               "6643.TWO",
  "VeriSilicon":                  "688521.SS",
  "Espressif Systems":            "688018.SS",
  "GigaDevice Semiconductor":     "603986.SS",
  "Horizon Robotics":             "9660.HK",
  "Cambricon Technologies":       "688256.SS",

  // ── T2 · Foundries, IDMs & OSATs (new) ──────────────────────────────────────────────
  "Loongson Technology":          "688047.SS",
  "Allwinner Technology":         "300458.SZ",
  "Vishay Intertechnology":       "VSH",
  "Littelfuse":                   "LFUS",
  "ams OSRAM":                    "AMS.SW",
  "Macronix International":       "2337.TW",
  "Winbond Electronics":          "2344.TW",
  "Powerchip Semiconductor Mfg Corp":"6770.TW",
  "Magnachip Semiconductor":      "MX",
  "Hangzhou Silan Microelectronics":"600460.SS",
  "Fuji Electric":                "6504.T",
  "Mitsubishi Electric":          "6503.T",
  "Sanken Electric":              "6707.T",
  "Unisem":                       "UNISEM.KL",

  // ── T3 · Equipment (new) ──────────────────────────────────────────────
  "Inari Amertron":               "INARI.KL",
  "CG Semi":                      "CGPOWER.NS",
  "Lasertec Corporation":         "6920.T",
  "Ulvac Inc":                    "6728.T",
  "Mycronic AB":                  "MYCR.ST",
  "Oxford Instruments":           "OXIG.L",
  "Aixtron SE":                   "AIXA.DE",
  "Chroma ATE":                   "2360.TW",
  "Aehr Test Systems":            "AEHR",
  "inTEST Corporation":           "INTT",
  "Bruker Corporation":           "BRKR",

  // ── T4 · Subsystems (new) ──────────────────────────────────────────────
  "Thermo Fisher Scientific":     "TMO",
  "Test Research Inc":            "6209.TW",
  "Lumentum Holdings":            "LITE",
  "nLIGHT Inc":                   "LASR",
  "Han's Laser":                  "002008.SZ",
  "Agilent Technologies":         "A",
  "Hamamatsu Photonics":          "6965.T",
  "Donaldson Company":            "DCI",
  "Daikin Industries":            "6367.T",
  "Johnson Controls":             "JCI",
  "Trane Technologies":           "TT",
  "NGK Insulators":               "5333.T",
  "Keyence Corporation":          "6861.T",
  "Omron Corporation":            "6645.T",
  "Eaton Corporation":            "ETN",
  "Vertiv Holdings":              "VRT",
  "Schneider Electric":           "SU.PA",

  // ── T5 · Components (new) ──────────────────────────────────────────────
  "ABB Ltd":                      "ABBN.SW",
  "Trelleborg Sealing Solutions": "TRELB.ST",
  "AMETEK Inc":                   "AME",
  "3M Company":                   "MMM",
  "Nidec Corporation":            "6594.T",
  "Allied Motion Technologies":   "AMOT",
  "Amphenol Corporation":         "APH",
  "TE Connectivity":              "TEL",
  "Schaeffler Group":             "SHA.DE",
  "RBC Bearings":                 "RBC",
  "Nippon Electric Glass":        "5214.T",
  "CTS Corporation":              "CTS",
  "Furukawa Electric":            "5801.T",
  "Sumitomo Electric Industries": "5802.T",
  "Fujikura Ltd":                 "5803.T",
  "Sensata Technologies":         "ST",

  // ── T6 · Materials (new) ──────────────────────────────────────────────
  "TT Electronics":               "TTG.L",
  "Largan Precision":             "3008.TW",
  "Soitec":                       "SOI.PA",
  "Celanese Corporation":         "CE",
  "Eternal Materials":            "1717.TW",
  "Samsung Electro-Mechanics":    "009150.KS",
  "LG Innotek":                   "011070.KS",
  "Daeduck Electronics":          "008060.KS",
  "Zhen Ding Technology":         "4958.TW",
  "TTM Technologies":             "TTMI",
  "Mitsui High-tec":              "6966.T",
  "Toray Industries":             "3402.T",
  "Mitsubishi Chemical Group":    "4188.T",
  "Sumitomo Bakelite":            "4203.T",
  "Mitsubishi Gas Chemical":      "4182.T",
  "Kureha Corporation":           "4023.T",
  "Avantor Inc":                  "AVTR",
  "AXT Inc":                      "AXTI",
  "IQE plc":                      "IQE.L",
  "Kuraray Co":                   "3405.T",
  "DIC Corporation":              "4631.T",

  // ── T7 · Mining & Extraction (new) ──────────────────────────────────────────────
  "Daicel Corporation":           "4202.T",
  "Hansol Chemical":              "014680.KS",
  "First Quantum Minerals":       "FM.TO",
  "Teck Resources":               "TECK",
  "KGHM Polska Miedz":            "KGH.WA",
  "Zijin Mining Group":           "601899.SS",
  "Ganfeng Lithium":              "002460.SZ",
  "Tianqi Lithium":               "002466.SZ",
  "Pilbara Minerals":             "PLS.AX",
  "China Molybdenum":             "603993.SS",
  "Eramet":                       "ERA.PA",
  "China Hongqiao Group":         "1378.HK",
  "Chalco":                       "601600.SS",
  "UC Rusal":                     "0486.HK",
  "LyondellBasell Industries":    "LYB",
  "Eastman Chemical Company":     "EMN",
  "LG Chem":                      "051910.KS",
  "Hanwha Solutions":             "009830.KS",
  "Lotte Chemical":               "011170.KS",
  "Sinopec":                      "600028.SS",
  "PetroChina":                   "601857.SS",
  "Reliance Industries":          "RELIANCE.NS",
  "South32":                      "S32.AX",
  "Newmont Corporation":          "NEM",
  "Barrick Gold":                 "GOLD",
  "Vedanta Limited":              "VEDL.NS",
  "Idemitsu Kosan":               "5019.T",
  "Almonty Industries":           "AII.TO",
  "5N Plus Inc":                  "VNP.TO",
  "Yunnan Tin Group":             "000960.SZ",
  "Imerys":                       "NK.PA",
  "Shenghe Resources":            "600392.SS",
  "Energy Fuels Inc":             "UUUU",
}